#ifndef INPUT_TEST__TESTMODE_H_
#define INPUT_TEST__TESTMODE_H_

enum TestMode {
  SCANF = 1,
  CIN_SYNC_WITH_STDIO_TRUE,
  CIN_SYNC_WITH_STDIO_FALSE,
  CIN_SYNC_WITH_STDIO_FALSE_TIE_NULLPTR
};

#endif //INPUT_TEST__TESTMODE_H_
